{
  "formatVersion": "1.1",
  "component": {
    "group": "xjtlu.cpt111",
    "module": "xjtlu.cpt111.assignment.quiz.lib",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xjtlu.cpt111.assignment.quiz.lib-0.0.1.jar",
          "url": "xjtlu.cpt111.assignment.quiz.lib-0.0.1.jar",
          "size": 19500,
          "sha512": "90842320ba6ed83a04b7c02895e7426da679f5178ec594b0f61d410c02de17f925c86cfbffc2d1990aa841d47e405412ccb2e7d5f110fda2b77a740b3dd1749f",
          "sha256": "3dd4a9dd97997b0b3cd8b02a6de76db4bdca39c65d2872bc6e2603c5f94bbd49",
          "sha1": "14864083bccd464f25522f9ed4944a916fcf410d",
          "md5": "486b8125ff0830dfc0fd05175c007d05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xjtlu.cpt111.assignment.quiz.lib-0.0.1.jar",
          "url": "xjtlu.cpt111.assignment.quiz.lib-0.0.1.jar",
          "size": 19500,
          "sha512": "90842320ba6ed83a04b7c02895e7426da679f5178ec594b0f61d410c02de17f925c86cfbffc2d1990aa841d47e405412ccb2e7d5f110fda2b77a740b3dd1749f",
          "sha256": "3dd4a9dd97997b0b3cd8b02a6de76db4bdca39c65d2872bc6e2603c5f94bbd49",
          "sha1": "14864083bccd464f25522f9ed4944a916fcf410d",
          "md5": "486b8125ff0830dfc0fd05175c007d05"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xjtlu.cpt111.assignment.quiz.lib-0.0.1-javadoc.jar",
          "url": "xjtlu.cpt111.assignment.quiz.lib-0.0.1-javadoc.jar",
          "size": 4224894,
          "sha512": "a20467f2f07097c025755a5baf536108052829e60067e9b47e42f91bebe33ddb6c8411d8d0a433ca2e64b71827a4448d83693279392cb7c99713e7956b37f45e",
          "sha256": "f46d3b215385f2ef0c7bbf6768840d255d87e1832356fe5777e9d4a8d2d548c0",
          "sha1": "8bc565eeb3ba092a55d13855d7b7b0d19d6402bb",
          "md5": "935401ae0d3cc7aa501de8c72a98dfd4"
        }
      ]
    }
  ]
}
